Differentiable classical force field support
deepmodeling/DMFF pull request #12
Opened 2022-03-28 07:40 UTC by WangXinyan940

We propose to add the following features to DMFF:

- 'LennardJonesForce'
- 'CoulombPMEForce'
- 'CoulNoCutoffForce'
- 'CoulReactionFieldForce'
- 'HarmonicBondJaxForce'
- 'HarmonicAngleJaxForce'
- 'PeriodicTorsionJaxForce'

The following generators are added to support related cards in OpenMM type XML forcefield.
- 'HarmonicBondJaxGenerator'
- 'HarmonicAngleJaxGenerator'
- 'PeriodicTorsionJaxGenerator'
- 'NonbondJaxGenerator'

2022-03-28 09:59 UTC, Ericwang6 requested changes

2022-03-28 09:59 UTC, Ericwang6 commented on .gitignore
> +>>>>>>> 70756cd80617652580988e6ef6b04545df86f7ca
This should be solved...

2022-03-28 09:59 UTC, Ericwang6 commented on dmff/classical/inter.py
> +sys.path.append("/home/lijichen/work/DMFF")
Here should be solved

2022-03-30 09:02 UTC, KuangYu requested changes
See comments in code.

2022-04-01 02:44 UTC, WangXinyan940 commented on dmff/classical/inter.py
> +        def get_energy(positions, box, pairs, epsilon, sigma, epsfix, sigfix):
I'd like to input position/box in nm & kJ/mol in API, and then transfer to angstrom when creating potential function like this:

class ADMPDispGenerator:
    def createForce():
        def potential_fn(positions, box, pairs, params):
            position_ang = positions * 10.0 
            box_ang = box * 10.0
            E_sr = pot_fn_sr(
                position_ang, box_ang, pairs, mScales, a_list, b_list, q_list, c_list[0]
            )
            E_lr = pot_fn_lr(position_ang, box_ang, pairs, c_list.T, mScales)
            return E_sr - E_lr

Then we don't need to touch parameter preparing process.

2022-04-01 02:55 UTC, WangXinyan940 commented on dmff/classical/inter.py
> +            return jnp.sum(E_inter) - jnp.sum(E_excl)
OK. Making change now.

2022-04-04 07:22 UTC, KuangYu commented on dmff/classical/inter.py
> +        def get_energy(positions, box, pairs, epsilon, sigma, epsfix, sigfix):
This is good. So let's make it a rule:

2022-04-10 18:42 UTC, merged