restructure project; add setup.py
deepmodeling/DMFF pull request #2
Opened 2022-02-18 08:46 UTC by Roy-Kid

2022-02-18 09:21 UTC, KuangYu commented on dmff/admp/README.md
> +# ADMP
Put this into docs?

2022-02-18 09:27 UTC, KuangYu commented on dmff/admp/settings.py
> +if PRECISION == 'double':
Some of these settings are not admp-specific, and should be global.
Considering moving settings.py under dmff folder, instead of admp

2022-02-18 09:28 UTC, KuangYu commented on examples/water_1024/run_admp.py
> +import admp.settings
Here they all should be import dmff.admp.*?

2022-02-18 09:29 UTC, KuangYu commented on examples/water_pol_1024/run_admp.py
> +from admp.multipole import convert_cart2harm
Similarly here, need to change to dmff.admp

2022-02-18 09:29 UTC, KuangYu commented on tests/test_multipole.py
> +from admp.multipole import convert_cart2harm
Here too

2022-02-18 09:31 UTC, KuangYu requested changes
See my comments in files

2022-02-19 10:29 UTC, Roy-Kid commented
1. Put the admp/settings.py under the dmff as a global setting file;
2. Add another settings.py under the admp as the admp's setting;
3. fix the import issue in the examples;
4. add docs with mkdocs supporting(I do this in the newton so I have not tested it yet, but built a rough framework).

2022-02-20 03:26 UTC, KuangYu approved these changes

2022-02-20 03:26 UTC, merged