Fluctuated leading term water force field
deepmodeling/DMFF pull request #31
Opened 2022-06-10 14:28 UTC by Humourist

modifications:
1.add read_input_info function in dmff.admp.parse.py to deal with info in pdb and xml files (input:pdb,xml output: multipoles/polarizabilities/tholes... and other atomic parameters)
2.use forcefield.xml instead of other xmls, add read_admp_xml in parser in order to read the new form of xml file
3.change line 795 in pme.py and add distribute_matrix in pairwise.py in order to wrap a jit outside my admp_calculator

2022-06-11 02:27 UTC, KuangYu requested changes

2022-06-11 02:27 UTC, KuangYu commented on examples/fluctuated_leading_term_waterff/forcefield.xml
> +             oXXX="0.0" oXXY="0.0" oXYY="0.0" oYYY="0.0" oXXZ="0.0000" oXYZ="0.0" oYYZ="0.00000" oXZZ="0.0" oYZZ="0.0" oZZZ="-0.0000"
Remove the octupole lines to avoid confusion, we do not support octupoles now

2022-06-11 02:27 UTC, KuangYu commented on examples/fluctuated_leading_term_waterff/forcefield.xml
> +             oXXX="0.0" oXXY="0.0" oXYY="0.0" oYYY="0.0" oXXZ="0.0" oXYZ="0.0" oYYZ="0.0" oXZZ="0.0" oYZZ="0.0" oZZZ="0.0"
This line too

2022-06-11 02:27 UTC, KuangYu commented on examples/fluctuated_leading_term_waterff/tmp
> +Traced<ConcreteArray([-0.7778535   0.38892674  0.38892674 -0.7754795   0.38773975  0.38773975], dtype=float32)>with<JVPTrace(level=2/0)> with
Remove all the tmp file, keep it clean

2022-06-11 02:27 UTC, KuangYu commented on examples/fluctuated_leading_term_waterff/run.py
> +def admp_calculator(positions, Q_local, axis_type, axis_indices, box, covalent_map, pol, tholes, c_list, q_list, a_list, b_list, pairs, rc):
Use standard api to obtain potential functions.

2022-06-11 12:47 UTC, Ericwang6 commented
@Humourist Plz remove `.forcefield.xml.swp` temp files

2022-06-14 03:28 UTC, KuangYu approved these changes

2022-06-14 05:09 UTC, merged